### ISSUE TITLE
Bug: java.lang.IllegalArgumentException: Problem decoding into existing bitmap

### ISSUE THREAD

**Issue by agent-polyblank** [p-lr/MapComposeMP#19]
Hi, I'm receiving the following crash on scrolling on an emulated device:

```
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  java.lang.IllegalArgumentException: Problem decoding into existing bitmap
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:769)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at ovh.plrapps.mapcompose.utils.Source_androidKt.toImage(Source.android.kt:19)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at ovh.plrapps.mapcompose.core.TileCollector$worker$1.invokeSuspend(TileCollector.kt:132)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
2024-12-11 23:31:01.956  9779-9813  System.err              org.king.openzedmaps.androidApp      W  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
2024-12-11 23:31:01.965  9779-9809  AndroidRuntime          org.king.openzedmaps.androidApp      E  FATAL EXCEPTION: TileCanvasThread
                                                                                                    Process: org.king.openzedmaps.androidApp, PID: 9779
                                                                                                    java.lang.IllegalArgumentException: Problem decoding into existing bitmap
                                                                                                    	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:769)
                                                                                                    	at ovh.plrapps.mapcompose.utils.Source_androidKt.toImage(Source.android.kt:19)
                                                                                                    	at ovh.plrapps.mapcompose.core.TileCollector$worker$1.invokeSuspend(TileCollector.kt:132)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@cc42ada, java.util.concurrent.ScheduledThreadPoolExecutor@330db0b[Running, pool size = 1, active threads = 1, queued tasks = 1, completed tasks = 352]]
2024-12-11 23:31:01.983  9779-9809  Process                 org.king.openzedmaps.androidApp      I  Sending signal. PID: 9779 SIG: 9
```

Emulator specs:

```
Properties
avd.ini.displayname              Rooted AVD
avd.ini.encoding                 UTF-8
AvdId                            Rooted_AVD
disk.dataPartition.size          6G
fastboot.chosenSnapshotFile      
fastboot.forceChosenSnapshotBoot no
fastboot.forceColdBoot           no
fastboot.forceFastBoot           yes
hw.accelerometer                 yes
hw.arc                           false
hw.audioInput                    yes
hw.battery                       yes
hw.camera.back                   virtualscene
hw.camera.front                  emulated
hw.cpu.ncore                     4
hw.device.hash2                  MD5:d1059e12633e5f5c541cb4a6eac71aeb
hw.device.manufacturer           Google
hw.device.name                   pixel_8_pro
hw.dPad                          no
hw.gps                           yes
hw.gpu.enabled                   yes
hw.gpu.mode                      auto
hw.initialOrientation            portrait
hw.keyboard                      yes
hw.lcd.density                   480
hw.lcd.height                    2992
hw.lcd.width                     1344
hw.mainKeys                      no
hw.ramSize                       2048
hw.sdCard                        yes
hw.sensors.orientation           yes
hw.sensors.proximity             yes
hw.trackBall                     no
image.androidVersion.api         30
image.sysdir.1                   system-images/android-30/google_apis_playstore/arm64-v8a/
PlayStore.enabled                true
runtime.network.latency          none
runtime.network.speed            full
showDeviceFrame                  yes
skin.dynamic                     yes
tag.display                      Google Play
tag.displaynames                 Google Play
tag.id                           google_apis_playstore
tag.ids                          google_apis_playstore
vm.heapSize                      256
```

Here is my tile provider:

```kotlin
...
    private fun getTileStreamProvider(): TileStreamProvider {
        val mapFloorLevel = 0
        val fileFormat = "jpg"
        val mapUrl = "https://map.projectzomboid.com/maps/SurvivalB417812"

        return TileStreamProvider { row, col, zoomLvl ->
            try {
                val url =
                    "${mapUrl}L${mapFloorLevel}/map_files/${zoomLvl}/${col}_${row}.${fileFormat}"
                val responseChannel = client.get(url).bodyAsChannel()
                responseChannel.readBuffer.buffered()
            } catch (e: Exception) {
                e.printStackTrace()
                null
            }
        }
    }
```

Here is my map state:
```kotlin
    val state =
        MapState(
            23,
            fullWidth,
            fullHeight,
            workerCount = 16,
            tileSize = 1024,
        ) {
            scale(1f)
            minimumScaleMode(Fill)
        }.apply {
            shouldLoopScale = false
            addLayer(tileStreamProvider, placement = BelowAll)
        }
}
```

And here is my map instance:

```kotlin
MapUI(state = viewModel.state)
```

I'm using KTor rather than Java httpio in my code but I am still getting back a buffered `Source` object so I'm not really sure why that would make a difference. I also get some tiles rendered but others not before the crash.  Help would be greatly appreciated! Cheers :)

**Comment by p-lr** [comment]
Hi, it looks like some tiles don't fit in previously allocated memory for other tiles. The library tries to reduce memory allocations by reusing existing "slots" when decoding a tile. 

To check if this is indeed the issue, you will have to disable this feature by changing those lines in `TileCollector.kt` L.133:
```kotlin
val image = resultBitmap.toImage(
      tilePool.get(),
      bitmapConfiguration.highFidelityColors
) ?: continue
```
to:
```kotlin
val image = resultBitmap.toImage(
      null,
      bitmapConfiguration.highFidelityColors
) ?: continue
```

Please report back the result. If this fixes your issue, then your tiles of level 0 don't have uniform encoding and tile pooling cannot be easily achieved. A change to the library will be required to defend against that.

**Comment by agent-polyblank** [comment]
Cheers for the quick response! I'll have a go this evening and get back to you :)

**Comment by agent-polyblank** [comment]
I had a go at this this evening. I'm having a bit of trouble importing the library locally. I have it in the root of my project and I've added it to `settings.gradle.kts`

```
implementation(":MapComposeMP")
```

But when I try a gradle sync I get the following:

```
e: ...MapComposeMP/build.gradle.kts:4:24: Unresolved reference: androidApplication
e: ...MapComposeMP/build.gradle.kts:5:24: Unresolved reference: androidLibrary
e: ...MapComposeMP/build.gradle.kts:6:24: Unresolved reference: jetbrainsCompose
e: ...MapComposeMP/build.gradle.kts:7:24: Unresolved reference: kotlinMultiplatform
e: ...MapComposeMP/build.gradle.kts:8:24: Unresolved reference: composeCompiler
```
Gradle doesn't seem to pick up the versions toml. Any ideas why?

**Comment by agent-polyblank** [comment]
Hi, I did some further investigation and I arrived at the conclusion that the crash was occurring because the top level map tiles i.e. row 0-1, col 0-1. zoom 0 were larger than the lower levels of tiles on my map I managed to fix this in my use case by enforcing a min scale. 

```kotlin
    val state =
        MapState(
            23,
            fullWidth,
            fullHeight,
            workerCount = 32,
            tileSize = 1024,
        ).apply {
            shouldLoopScale = true
            addLayer(tileStreamProvider!!, placement = BelowAll)
            minimumScaleMode = Forced(0.01f)
            maxScale = 1f
            scale = 0.01f
            setMapBackground(Color.Black)
        }
```

Would it be worth making the tile-pool toggle-able? How bad would the performance impact of this be? Thanks very much for your help @p-lr  you definitely put me on the right track! :)

**Comment by p-lr** [comment]
Instead of entirely toogling off the tile-pool, it should be possible to make a first attempt with using it - and if it fails, fallback to new tile allocation.
I'll make the change.
I'm curious, do you plan to use the library on an ios device ?

**Comment by agent-polyblank** [comment]
That would be good thank you! Happy to help if you'd like! 

I am planning on a multiplatform app. I've not tested it on iOS yet though.

**Comment by p-lr** [comment]
Thanks, I have made the changes. However, I'm having an issue during the publication process on maven. The gradle task of some "iosArm64 bundle" signature is failing. While there's absolutely no issues on android, desktop or other targets, I cannot publish a new version of the lib without the ios artifacts.

**Comment by agent-polyblank** [comment]
Amazing thank you so much!
